# docker-compose -f docker-compose.yml -p my-mqtt-project up

version: '3.7'

services:

  mosquitto:
    image: eclipse-mosquitto:1.6.15  
    # ports:
    #   - 1883:1883
    volumes:
    - /mosquitto/config
    - /mosquitto/data
    - /mosquitto/log
    network_mode: "host" 