version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"  # MQTT port
    volumes:
      - eclipse-mosquitto-data:/mosquitto/config
      - eclipse-mosquitto-data:/mosquitto/data
      - eclipse-mosquitto-data:/mosquitto/log
    restart: always

volumes:
  eclipse-mosquitto-data:
