version: '3.3'

services:

  mongo:
    image: eclipse-mosquitto:1.6.15    
    container_name: eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883
    volumes:
    - /mosquitto/config
    - /mosquitto/data
    - /mosquitto/log
